---
  - name: Copiando arquivo de instalação
    copy: src=zabbix-agent-4.0.18-1.el{{ ansible_distribution_major_version }}.x86_64.rpm dest=/tmp/zabbix-agent-4.0.18-1.el{{ ansible_distribution_major_version }}.x86_64.rpm

  - name: Instalando Zabbix Agent
    shell: rpm -i /tmp/zabbix-agent-4.0.18-1.el{{ ansible_distribution_major_version }}.x86_64.rpm

