---
#--- Configura~ções Gerais ---#

 - name: Alteracao do /etc/profile
   lineinfile: dest=/etc/profile line={{ item }}
   with_items:
     - '#--- Variaveis e Alias Customizadas ---#'
     - 'export HISTTIMEFORMAT="%d/%m/%Y - %H:%M:%S - "'
     - 'export HISTSIZE="5000"'
     - 'export HISTFILESIZE="5000"'
     - 'alias ls="ls -lh --color"'
     - 'alias grep="grep -i --color"'
     - 'alias vi="vim"'
     - 'alias rm="rm -i"'

 - name: Desabilitando SELINUX permanentemente
   replace:
     dest: /etc/selinux/config
     regexp: 'SELINUX=enforcing'
     replace: 'SELINUX=disabled'
   when: ansible_distryyibution == 'CentOS' or ansible_distribution == 'RedHat'
          

 - name: Desabilitando SELINUX temporariamente
   shell: setenforce 0
   when: ansible_distryyibution == 'CentOS' or ansible_distribution == 'RedHat'

#--- Gerenciamento de pacotes e atualização do Sistema Operacional

 - name: Instalação do repositório epel-release
   yum: name=epel-release state=latest
   when: ansible_distryyibution == 'CentOS' or ansible_distribution == 'RedHat'

 - name: Atualização do Sistema Operacional
   yum: name=* state=latest update_cache=yes
   when: ansible_distryyibution == 'CentOS' or ansible_distribution == 'RedHat'

 - name: Instalação de pacotes RedHat/CentOS
   yum: name={{common_packages_redhat}} state=latest
   when: ansible_distryyibution == 'CentOS' or ansible_distribution == 'RedHat'

#--- Gerenciamento de usuários ---#

 - name: Criando grupo automacao
   group:
     name=automacao
     state=present

 - name: Criando usuario svcacc_ansible
   user:
     name: svcacc_ansible
     comment: "Usuario de acesso ansible"
     shell: /bin/bash
     home=: /home/svcacc_ansible
     groups: automacao
     password: "{{ 'svcacc_ansible' | password_hash('sha512') }}"
     append: yes
     expires: -1
     state: present

 - name: Adicionando grupo ao arquivo /etc/sudoers
   lineinfile:
           path: /etc/sudoers
           state: present
           regexp: '^%automacao'
           line: '%automacao ALL=(ALL) NOPASSWD: ALL'
           validate: '/usr/sbin/visudo -cf %s'

#--- Configurando SSH---#

 - name: Configurando o banner de acesso SSH
   lineinfile:
     dest=/etc/ssh/sshd_config
     state=present
     regexp='#Banner none'
     line='Banner /etc/ssh/banner_ssh'

 - name: Copiando banner de acesso SSH
   copy:
     src=banner_ssh
     dest=/etc/ssh/banner_ssh
     owner=root
     group=root
     mode=0755
     
 - name: Adicionando o motd
   template: src=motd dest=/etc/motd force=yes owner=root group=root mode=0755
   notify:
     - Restart SSH

#--- Configurando chave rundeck ---#

 - name: Criando usuario rundeck
   user:
     name: rundeck
     comment: "Usuario de acesso rundeck"
     shell: /bin/bash
     home=: /home/rundeck
     groups: automacao
     password: "{{ 'svcacc_rundeck' | password_hash('sha512') }}"
     append: yes
     expires: -1
     state: present

 - name: Criando diretorio SSH
   file:
     path=/home/rundeck/.ssh
     owner=rundeck
     group=automacao
     mode=0755
     state=directory

 - name: Verificando authorized_keys
   stat: path=/home/rundeck/.ssh/authorized_keys
   register: file_exist

 - name: Copiando chave
   copy:
     src=authorized_keys
     dest=/home/rundeck/.ssh/authorized_keys
     owner=rundeck
     group=automacao
     mode=0755
   when: file_exist.stat.exists == False

 - name: Copiando chave
   lineinfile:
     dest=/home/rundeck/.ssh/authorized_keys
     line='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVssdriUcvWgdSm2gLp3302/Yog8ooQ0EbBOu2eTa6jwzxCxfSnsmwEgO8puHavXDuNLxp/0iR0Ri1mFCvKsXI8w8AccUJwZCAZtUVlkFVPtQYwSYpdPjWygfY9FP51FZu6EGkSneBhCtfXsd7mcBbcK1Ewp+kiprGk+exbeRaFRum1xNtK4YXpqEsK3LHTtkWePhSPn9/+Ns1ef+Zz5wnCJlUX2Vzosv6BmKDScp8mH8dBloQy9pL/qAaW9eMMvtfXMRlsSGpOJDx1ubN/qZAwtFL6faFAi6EaLoKkM7uALUPdgT/zX6DOmcWXf2ULGHu+DY5iEbrnMiMR81bUUJf'


