---
 - name: Gerenciamento de Serviço
   hosts: servico
   become_method: sudo
   become: true
   tasks:

   - name: Serviço Linux
     service:
       name: "{{ service_name }}"
       state: "{{ service_type }}"
     when: 
       - ansible_system == "Linux"

   - name: Serviço Windows
     win_service:
       name: "{{ service_name }}"
       state: "{{ service_type }}"
     when: 
       - ansible_system == "Windows"
