---
- name: ADD User
  hosts: "{{ destinos }}"
  tasks:

  - name: Enable Winrm step 1
    win_shell: winrm set winrm/config/service/auth '@{Basic="true"}'

  - name: Enable Winrm step 2
    win_shell: winrm set winrm/config/service '@{AllowUnencrypted="true"}'
