---
- name: Adicionando macros aos hosts do arquivo /tmp/arquivo.csv
  hosts: rundeck
  tasks:
 
  - name: Criando macros no host teste10
    local_action:
        module: zabbix_hostmacro
        server_url: http://ip:port
        login_user: user
        login_password: senha
        host_name: hostname
        macro_name: PORT
        macro_value: value
        state: present
